Updated pydlm for compatibility with python3.10
Updated an import from `collections` so that the package is compatible with `python3.10`. 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from pydlm import dlm, trend, seasonality, dynamic, autoReg, longSeason

File ~/repos/oak/.oak/lib/python3.10/site-packages/pydlm/__init__.py:8
      6 from pydlm.modeler.trends import trend
      7 from pydlm.modeler.seasonality import seasonality
----> 8 from pydlm.modeler.dynamic import dynamic
      9 from pydlm.modeler.autoReg import autoReg
     10 from pydlm.modeler.longSeason import longSeason

File ~/repos/oak/.oak/lib/python3.10/site-packages/pydlm/modeler/dynamic.py:18
      1 """
      2 =========================================================================
      3 
   (...)
     15 
     16 """
     17 import numpy as np
---> 18 from collections import MutableSequence
     19 from copy import deepcopy
     21 import pydlm.base.tools as tl

ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```